[package]
name = "move-binary-format-wasm"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
move-binary-format = { path = "../../external-crates/move/move-binary-format", features = ["wasm"] }
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = "0.2.62"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
getrandom = "0.2.9"
js-sys = "0.3.61"
hex = "0.4.3"

[lib]
crate-type = ["cdylib"]
